# PDF Download Service Configuration

# PDF Download settings
download:
  base_url: "https://sadcsapi.bydauto.com/file/download?fileUrl="
  # storage_path: "/mnt/sdb/bgate/pdf-claims/"  # Production path
  storage_path: "/home/pcampos/bgate/pdf-claims/"  # Paulo's local path
  
  # Download behavior settings
  timeout_seconds: 60
  retry_attempts: 3
  retry_delay_seconds: 5
  delay_between_downloads: 1  # seconds between file downloads
  delay_between_claims: 2     # seconds between processing different claims

# Scheduler settings
scheduler:
  # Run the check every 2 hours. You can also use 'minutes' or 'seconds'.
  periodicity_hours: 2
  
  # Prevent overlapping jobs
  max_instances: 1

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "pdf_download_service.log"
  max_file_size_mb: 100
  backup_count: 5

# Monitoring and maintenance
monitoring:
  # Enable statistics logging
  log_statistics: true
  statistics_interval_hours: 24
  
  # Clean up old failed records
  cleanup_enabled: true
  cleanup_interval_days: 7
  cleanup_retention_days: 30

# API settings
api:
  headers:
    User-Agent: "BYD-PDF-Download-Service/1.0"
    Accept: "application/pdf"
    APP_ID: "791565299"
    SECRET_KEY: "1a0fe9add8e3304fb6195d37f3b313bf1ad766d455706ade26f79018c685beed"
  
  # Rate limiting
  requests_per_minute: 60
  
  # Connection settings
  verify_ssl: true
  allow_redirects: true

# Error handling
error_handling:
  # How many consecutive failures before alerting
  max_consecutive_failures: 10
  
  # Whether to continue processing other files if one fails
  continue_on_error: true
  
  # Whether to retry failed downloads in the next cycle
  retry_failed_downloads: true

# File validation
file_validation:
  # Minimum file size in bytes (to detect empty or corrupted downloads)
  min_file_size: 1024  # 1KB
  
  # Maximum file size in bytes (to detect potential issues)
  max_file_size: 104857600  # 100MB
  
  # Whether to validate PDF headers
  validate_pdf_format: true

# Performance settings
performance:
  # Database connection pool settings
  db_pool_size: 5
  db_pool_timeout: 60
  
  # Batch processing settings
  batch_size: 20  # Process this many files before committing to DB
  
  # Memory management
  max_memory_usage_mb: 1024
