CREATE TABLE PDF_DOWNLOAD_DMS_CLAIMS (
    FILE_ID VARCHAR2(255) PRIMARY KEY,
    CLAIM_ID NUMBER(20) NOT NULL,
    CLAIM_NO VARCHAR2(100),
    REMOTE_FILE_NAME VARCHAR2(255),
    LOCAL_FILE_PATH VARCHAR2(1000) NOT NULL,
    DOWNLOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('SUCCESS', 'FAILED')),
    ERROR_MESSAGE VARCHAR2(2000)
);

-- Optional: Create an index on CLAIM_ID for faster lookups
CREATE INDEX IDX_PDF_CLAIM_ID ON PDF_DOWNLOAD_DMS_CLAIMS (CLAIM_ID);
